# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-20 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.IntegerField(unique=True)),
                ('patient_id', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
