# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-21 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_id',
            field=models.IntegerField(),
        ),
    ]
