# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-22 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0002_auto_20200221_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
