# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-26 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0003_appointment_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=50, null=True)),
                ('default_pharmacy', models.CharField(blank=True, max_length=200, null=True)),
                ('cell_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('patient_photo', models.CharField(blank=True, max_length=400, null=True)),
                ('preferred_language', models.CharField(blank=True, max_length=200, null=True)),
                ('race', models.CharField(blank=True, max_length=50, null=True)),
                ('social_security_number', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
